### ISSUE TITLE
can change host ip??

### ISSUE THREAD

**Issue by nimabrave999** [Maxx53/SCMBot#252]
Hi all , the ping of the default host is pretty high.. any possibility to change the host ip for faster ping?? ty.. If im able to change it, where can i get the faster host ip??

**Comment by nimabrave999** [comment]
max please help

**Comment by nimabrave999** [comment]
@Maxx53 hi. how can i get the fast host ip for hosts.txt file? ty

**Comment by Maxx53** [comment]
https://github.com/Maxx53/SCMBot/issues/202
For other hosts, google "ping from other countries" and ping "steamcommunity.com"

**Comment by nimabrave999** [comment]
any format to edit the file?? i edit it and the host usage status turn blank..

**Comment by deltaformation** [comment]
you can also do
CMD
ping steamcommunity.com
get that ip address if it's at suitable IP
and replaced it with the IPs in hosts.txt
you can do cmd+ping steamcommunity.com again and see if there are any other IPs that you get with good ping.

**Comment by nimabrave999** [comment]
@deltaformation  thank you. cheers :-)
