### ISSUE TITLE
PLEASE SOMEONE REPLY

### ISSUE THREAD

**Issue by firebug11** [Maxx53/SCMBot#273]
I have this problem where i have been searching with the bot to try get a karambit doppler fn
I look at it and see a error within all the "Parsing fail" to see "item is not supported in html.
This gave me hope cause seeing that meant it tried to buy it before anyone else could and all i had to do was uncheck the box scan with html instead of json
When i un tick it it stats to search again, but after 5 mins or less it just spams the error "Json without data"
Im starting to lose hope and no one is answering anything on these forums anymore...

**Comment by deltaformation** [comment]
you are trying to buy something that probably 1000s of people try to buy too, i'm sorry to say this but it won't be possible.

**Comment by firebug11** [comment]
Just got one 1, YAY! You were wrong my friend.
http://steamcommunity.com/profiles/76561198072659111/inventory/#730
