### ISSUE TITLE
Скомпилированный мною вариант не покупает вещи (Unknown error) а тот, что бинарником - работает без замечаний

### ISSUE THREAD

**Issue by uaBArt** [Maxx53/SCMBot#275]
Подскажите, что можно сделать, уже и ложил в папку с рабочим вариантом, с теми же настройками и куки запускал.
Когда компилирую в VS то мой скомпилированный вариант наотрез отказывается что-либо покупать. Компилирую последнюю версию тут. Также пробовал компилить на две версии выше, но то же самое...

**Comment by greenberg2** [comment]
Бинарники работают? / binary files work?

**Comment by uaBArt** [comment]
тот, что бинарником - работает без замечаний.
но хотелось бы свой вариант чтобы тоже работал...
мой скомпиленный работает, логиниться, парсит цены, но вот проблема в том, что покупать он наотрез отказывается из-за Unknown Error

**Comment by Maxx53** [comment]
https://github.com/Maxx53/SCMBot/issues/237

**Comment by greenberg2** [comment]
Макс, причем тут фикс?

**Comment by uaBArt** [comment]
Ох, спасибо, как только доберусь до ноута соберу, проверю...
Прошу сделать также коммит с фиксом, пожалуйста...
