### ISSUE TITLE
бот не подключается к стиму

### ISSUE THREAD

**Issue by koren30** [Maxx53/SCMBot#276]
Бот не подключается к стиму, всегда доходит до одного момента и все.
http://firepic.org/images/2015-03/01/tsw5clzwqhz6.png
все данные ввожу правильно

**Comment by uaBArt** [comment]
Вы пользуетесь скачанными бинарниками или собственно собранной версией?

**Comment by uaBArt** [comment]
предлагаю попробовать проверить hosts.txt или другой аккаунт

**Comment by koren30** [comment]
пользуюсь бинарником, с другого аккаунта входит без проблем

**Comment by uaBArt** [comment]
значит скорее всего данные неправильно вводишь... 
проверь с клиента...

**Comment by koren30** [comment]
тему можно закрывать. я забыл что у меня включен семейный просмотр

**Comment by uaBArt** [comment]
Сам закрой... только ты можешь и Maxx53
