### ISSUE TITLE
SCMBot упал

### ISSUE THREAD

**Issue by Punisher1337** [Maxx53/SCMBot#294]
Вообщем включаю бота и вылетает ошибка:
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.FormatException: Индекс (отсчитываемый от нуля) должен быть больше или равен нулю, но меньше размера списка аргументов.
   в System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   в System.String.Format(IFormatProvider provider, String format, Object[] args)
   в System.String.Format(String format, Object arg0, Object arg1, Object arg2)
   в SCMBot.Main.LoadSettings(Boolean loadtabs)
   в SCMBot.Main.Main_Load(Object sender, EventArgs e)
 

Заново скачал бота, поставил вещи на скан, но в окне лога, красной надписью пишет Parsing fail. Кто знает в чём проблема?

**Comment by AdamTeo** [comment]
'Parsing fail' пишет о предметах, которых в данный момент нет на площадке?

**Comment by Punisher1337** [comment]
Они есть на площадке

**Comment by Punisher1337** [comment]
Всё, проблема решилась сама собой.

**Comment by Maxx53** [comment]
@Punisher1337 себя магарыч
