### ISSUE TITLE
can i run this on my web-site?

### ISSUE THREAD

**Issue by AegonTheUnlikely** [Maxx53/SCMBot#305]
i dont know much coding but can i run this on my asp.net website so i can keep going while i was away from pc on my mobile phone.or is there anyway to do this?

**Comment by Maxx53** [comment]
Pretty sure you can, but after some modification.

**Comment by AegonTheUnlikely** [comment]
what kind of modifications?could you show me a guide for this issue?

**Comment by Maxx53** [comment]
Well, It's a big work! Google "winforms to asp.net".
