### ISSUE TITLE
hosts

### ISSUE THREAD

**Issue by torbalohas** [Maxx53/SCMBot#310]
Что это за хосты? Это прокси, днс или что это вообще? Где их взять кроме cmd-ping и гугл-пинг из других стран. Просто все что я впихну в документ hosts начинает эрорить Item is not supported in html source.

**Comment by kitzik** [comment]
ip стимовских серверов

**Comment by Maxx53** [comment]
удивительно, но некоторые пытаются добавлять даже игровые сервера.
речь идет о серверах торговой площадки (steamcommunity.com).
https://github.com/Maxx53/SCMBot/issues/202
