### ISSUE TITLE
Maxx53 Check this!

### ISSUE THREAD

**Issue by SneakySphynx** [Maxx53/SCMBot#312]
Im willing to donate to you if you talk me into perfect settings etc!
As a paypal gift, non refundable :)

Add my skype: Mahjiza

**Comment by Maxx53** [comment]
Perfect settings? Never heard about it. Sorry.

**Comment by SneakySphynx** [comment]
I just mean, set it up perfectly. Since im kinda new to this.

Up to you, add me if you want. :)

**Comment by SneakySphynx** [comment]
Can i use delay between requests at 0 ? or will that get me banned easier?
