### ISSUE TITLE
What

### ISSUE THREAD

**Issue by ryjoku** [Maxx53/SCMBot#314]
What i must type in Description field in Steam Guard Check window? Help me

**Comment by nimabrave999** [comment]
@ryjoku Morgan Freeman , Fuck You or just press the space bar.

**Comment by ryjoku** [comment]
kk ty, helped me a lot

2015-04-12 4:24 GMT+02:00 nimabrave999 <notifications@github.com>:

**Comment by nimabrave999** [comment]
@ryjoku no problem m8

**Comment by Maxx53** [comment]
thx m8
