### ISSUE TITLE
You are currently unable to use the Community Market on this device.Что делать?Два дня покупал и все было нормально

### ISSUE THREAD

**Issue by AmazingKill** [Maxx53/SCMBot#320]

**Comment by nimabrave999** [comment]
@AmazingKill Wait 7  days..

**Comment by AmazingKill** [comment]
Why?

**Comment by torbalohas** [comment]
Попробуй удалить файл Setings и coockies в папке с ботом, выйти из самого стима и перезагрузить компьютер. Потом залогинься сначала в боте, после чего в самом стиме. Мне помогло.

**Comment by AmazingKill** [comment]
Спасибо,помогло
