### ISSUE TITLE
Актуальность бота.

### ISSUE THREAD

**Issue by Vyshkvarko** [Maxx53/SCMBot#326]
Актуален ли еще бот ?
И работает ли он вообще ?
При попытке выставить бота на торг выдает след ошибки:
"You are currently unable to use the Community Market on this device" хотя торговая площадка ОТКРЫТА. В ручную я спокойно могу покупать или продавать предметы.
Или вот еще одна ошибка "Content empty".
Если бот все же актуален, подскажите как исправить ошибки.

**Comment by Maxx53** [comment]
Не актуален.
Не работает.

**Comment by TheNega** [comment]
Maxx53, почему не актуален? Вроде как работает все.

**Comment by Maxx53** [comment]
@TheNega разработка прекращена пол года назад, а площадка продолжает обновляться, рано или поздно все сломается, если уже не сломалось (я даже не в курсе).

**Comment by TheNega** [comment]
Понятно. А платная/приватная версия не планируется? Например на офф.сайте программы , за некую сумму , думаю не помешали бы лишние финансы , ведь софт хорош даже сейчас , спустя пол года , но хотелось бы что бы он был по шустрее нынешнего. Я думаю спрос был бы неплохой.

**Comment by nomorepain** [comment]
Я думаю планируется посещение тобой дурдома...
