### ISSUE TITLE
You are currently unable to use the Community Market

### ISSUE THREAD

**Issue by Haunterrr** [Maxx53/SCMBot#333]
Все работало как часики, но стала появляться такая надпись и не покупает предмет...
Банов нету, ТП открыта (http://i.imgur.com/ickLk5P.png тому пруф)
В чем проблема? Подскажите пожалуйста
http://s011.radikal.ru/i316/1505/17/68ee76a62da2.jpg - Скрин

**Comment by Maxx53** [comment]
Учимся использовать поиск:
 https://github.com/Maxx53/SCMBot/issues?utf8=✓&q=You+are+currently+unable
