### ISSUE TITLE
Steam Guard Check

### ISSUE THREAD

**Issue by Radmil96** [Maxx53/SCMBot#335]
![default](https://cloud.githubusercontent.com/assets/12469080/7664804/829957fe-fbab-11e4-8ad7-d1447ac1c4ab.png)
Как быть с этим, подскажите пожалуйста. Сколько не вводил не получается.

**Comment by Maxx53** [comment]
Дальше своего носа не видишь?
https://github.com/Maxx53/SCMBot/issues/332
https://github.com/Maxx53/SCMBot/issues/327

**Comment by Radmil96** [comment]
Спасибо большое

2015-05-16 15:14 GMT+04:00 Maxx53 <notifications@github.com>:
