### ISSUE TITLE
Капча

### ISSUE THREAD

**Issue by Rocky54** [Maxx53/SCMBot#336]
Из за незнания английского я не смог прочитать что написано тут :( https://github.com/Maxx53/SCMBot/issues/327

Проблема всё та же, что и у всех. При нажатии на ЛОГИН выдаёт капчу которую бот не принимает.... Что делать?

**Comment by Maxx53** [comment]
ты что, слепой совсем?
https://github.com/Maxx53/SCMBot/issues/332

**Comment by Rocky54** [comment]
Возможно..... Или может быть глупый... Но я так и не понял что сделать что бы убрать капчу. Туда кудда вы меня направили там даётся сылка на вопрос https://github.com/Maxx53/SCMBot/issues/327 и там английский.... буду очень благодарен если поможете :)

**Comment by Maxx53** [comment]
Куда я направил, черным по белому напечатано - пробуй последний бинарник. Ссылка на главной станице репозитория и на сайте проекта. 
На всякий случай, оставлю ее еще и здесь: http://scmbot.ru/uploads/scmbot_bin.rar

**Comment by Rocky54** [comment]
Спасибо огромное. Заработал)))
