### ISSUE TITLE
 Captcha still not working

### ISSUE THREAD

**Issue by sebmins** [Maxx53/SCMBot#337]
In FAQ it says wait a while and then try again. Its been almost a week and doesn't work. When I click to  open it up this message always comes up http://i.imgur.com/y4FgM5R.png shouldn't it only come up once?

**Comment by Maxx53** [comment]
Wait... Waaat?
1) FAQ is out of date.
2) https://github.com/Maxx53/SCMBot/issues/327

**Comment by sebmins** [comment]
Lord thank you
