### ISSUE TITLE
There was a problem purchasing your item

### ISSUE THREAD

**Issue by sebmins** [Maxx53/SCMBot#344]
This is issue #199 , I'm getting the same problem. Maxx said "Remove old "cookie.dat" (backup it!), then try to login with new steam guard activation." 
Unfortunately I am not adapt at coding, I even asked my brother who does computer science at uni and he didn't know what to do.
So basically, how do I remove the cookie.dat?

**Comment by Maxx53** [comment]
Tee-hee, computer science, damn, sounds awesome.
File "coockies.dat" in program's folder. It's all about it.
