### ISSUE TITLE
Q: HTML not supported error (not urgent, just curious)

### ISSUE THREAD

**Issue by mtzi** [Maxx53/SCMBot#363]
Its been a while since i noticed i get 1 random "HTLM not supported" error.
Not at standard times, not on standard item. just RANDOM
I tried to check the code to see what makes the program give that specific error and didnt manage a lot.
Read here but didnt find much.
Do you think that this 1 random error could be a new listing that was bought before my instance of the program saw it?

**Comment by mtzi** [comment]
http://imgur.com/a/KK8Vl
Here, imgur link, dota2 arcana + 2 csgo knives

**Comment by vampig** [comment]
this message appears when steam host blocks your request. often, 'cause previous request not yet get answer. try to use different hosts.

**Comment by greenberg2** [comment]
Crawl through the connection to different machines is long outdated. The whole cluster has a common base.
