### ISSUE TITLE
Scanning Prices

### ISSUE THREAD

**Issue by Sqveeze** [Maxx53/SCMBot#364]
Hello,

This program is very nice, i want to use it for buy underpriced/mistyped price Butterfly Knife's. My only question is when the program scan for price, how the scan goes? I mean i have all the butterfly knife added to the scanning list, so i think that's over 40+ scan / 3 seconds, that's a bit too much and steam can detect it as bot?

**Comment by mtzi** [comment]
Even with 1 item, after 24 hours steam knows u have bot.
There is not 1 person on the planet who can sit on computer 24hours and click "refresh" on website.
They just dont do anything to stop you. Even botting sells items on market = they get money from it (th 15% cut, or whatever they get). if they ban all bots they make less money.
Anyway, to your question, they can detect your bot about 1 day after u start using, no matter how many items. if 40 items, steam community market might start giving errors "item not supported in HTML", "Move along..." etc. if u see many errors u scan too fast

**Comment by Sqveeze** [comment]
Hm... but i'm not going to run it 24/7, more like 16-20 / 7. Anyway 3 second on every items do the trick or should i increase that?

**Comment by mtzi** [comment]
If u get errors (see right side of program) and not numbers of prices u should increase that
if u dont get errors u are fine

**Comment by Sqveeze** [comment]
Oh one more question, if i go play CS:GO while the program runs will i get VAC ban or anything?

**Comment by mtzi** [comment]
i run the bot for 15 days or something. i play CSGO, all good.

**Comment by Maxx53** [comment]
@Sqveeze no, program works jist like your webbrowser, no any process injecting.
@mtzi thx m8.

**Comment by Sqveeze** [comment]
@mtzi 
@Maxx53 

Thanks for both of you guys! Sorry for lame questions.
