### ISSUE TITLE
Buying items that are rarely on the market...

### ISSUE THREAD

**Issue by Alex1os** [Maxx53/SCMBot#367]
Hey Everyone,

first of all i would like to say big thanks to Maxx for making this incredible cool tool, u saved me alot of cash :-).

I could use some help here. Since about 3 days I am trying to scan/buy some csgo knives (karambit marble fade/fade/tiger tooth etc.) The problem is that these knives only appear on the market about 3 times a day. And I didn't get one of them yet. Either I'm getting outbotted or I failed to give the items the right link or name. I got confused because of the star in the name of the csgo knives. My browser renames this link: http://steamcommunity.com/market/listings/730/★%20Karambit%20%7C%20Marble%20Fade%20%28Factory%20New%29
into this: http://steamcommunity.com/market/listings/730/%E2%98%85%20Karambit%20%7C%20Marble%20Fade%20%28Factory%20New%29

So I'm not sure if i have the right link for my scm bot on these items. And i always get "parsing fail" and i thought that this is normal because the items usually isn't on the maket...Btw i got the links to the items and names from http://steamcompanion.com/csgo/-Karambit--Marble-Fade-Factory-New/

If u guys could give me some help that would be nice. I'm just trying to get one of these knives thats all. 

Lg Alex

**Comment by mtzi** [comment]
If you open both links in chrome, they appear the same, so thats not a problem, the different must be that one link has the ASCII code for the star character. 
Parsing fail is normal. i get it too. Your delay seems to be a bit over 1 sec, getting a ping at 2 secs. 
I guess u have a high chance to get it when it comes on

**Comment by Alex1os** [comment]
Hello mtzi,

thanks for the fast response! I just saw that when I choose a knive form the scm bot list, it actually translates the ★ into %E2%98%85. And scm doesn't show the picture of the item since it didn't see it.
Glad to hear that u think I have a high chance on getting it. I wasn't sure about how fast i should go.

Lg Alex

**Comment by mtzi** [comment]
Im currently on the state of building up the wallet up to 400 so i can get such a knife. So letting me know if you are succesful would be really nice. Looking forward to it. Good luck. May the bot be with you

**Comment by Alex1os** [comment]
short update

I had scm run on my notebook with wifi and I noticed my pings were very unstable and I switched to direct connection to the modem/router. I have the hope that this may help.

Sadly, there seem to be other bots, maybe faster or on servers that seem to be extremly fast, faster than my scm bot with 50mbit network. I live in germany and maybe the server for these items is in the us...I don't know what to do. On steam companion I can see all buys that my bot didn't get.The last thing I can try to do is go full retard on the network settings on the scm bot.

The past 3 days I had seen about 15 knives go past and my bot didn't even see them. I'm rly loosing my hope here. Any advice would be great.

Lg Alex

**Comment by mtzi** [comment]
use a "ping from different locations" service, to determine the best ping servers from you (EU)
Then go to the SCM folder (where the .exe file is) and find the hosts file, rename it to something else
then make a new hosts.txt and copypaste the servers u saw on the 1st line of what i wrote after each server press enter and put the next one in the line below, max 15 servers
reopen SCMbot.
i had 120-300 ping on servers, and after i changed them i have 70-100.
hope it helps

**Comment by Alex1os** [comment]
Hey mtzi,

do mean sites like this one http://startping.com/ ? So all I need to do is enter some ip address like google.de and then add them in scm bot?

Btw somthing weird happened today. My scm bot actually saw one of the knifes today because the picture loaded but he didn't buy it lol.

Lg Alex

**Comment by Alex1os** [comment]
So I did what u mentioned. Here is the result:
![pingwtf](https://cloud.githubusercontent.com/assets/12844702/8132070/55f101e6-111f-11e5-9c84-dbe1323974c5.png)
For some weird reason i know get "html error" 90% of the time. Have u got an idea why?
I picked 15 different servers in my local area.

Lg Alex

**Comment by Alex1os** [comment]
Hey

So I checked everything and got a new list of ips running smoothly. :dancers: 
![hahaping](https://cloud.githubusercontent.com/assets/12844702/8137356/1569e182-1143-11e5-8a38-a675137ce083.png)

Now i just need to get that knife lol.

Lg Alex

**Comment by Alex1os** [comment]
It happened!!!
I had my bot only running on 3000ms and i got my dream knife today. I made a litte screenshot to show u proof.
![thedream](https://cloud.githubusercontent.com/assets/12844702/8140814/7e68f54e-115f-11e5-9e59-a2ec84985f20.png)

This is so awesome, this knife is worth sooooo many keys xD. Your idea with the ips with different servers worked wonders. Big thanks mate.

Cheers Alex hope u get ur dream knife

**Comment by mtzi** [comment]
GOD DAMN! thats my target too man. sitting at 1000keys or so! GJ! hope to get there soon enough

**Comment by eLqupe** [comment]
Hallo Alex1os. can u tell me where u find this numbers? and how u find it? i mean IP with 10 - 15 -16-25-10 18 ping. thank u

**Comment by Alex1os** [comment]
@mtzi 
yeah the kara tiger tooth ranges from 250k-300k depending on float value

@eLqupe 
it's actualy prety easy, all u have to do is llok for servers or websites and find their respctive ip address and then u have to put them into scm bot and test if they work, not all ips work with the bot

to find such ips for example open "cmd" in windows search and typ something like "ping www.google.com" and ur pc will ping that server and u can note that ip address
![cmd](https://cloud.githubusercontent.com/assets/12844702/8144355/502593aa-11db-11e5-844e-99c014f29f2f.png)

**Comment by eLqupe** [comment]
yea but how i can find ips good for me? idk steam ips. where Max take defoult ips? or i need take random ips and test it? )  i try do u IP on ss with low ping and only 2 works. other "html error" . what ips now do u have? how many? how many ping? sry bad eng

**Comment by mtzi** [comment]
go google. search "ping from different location"
click 1 site
ping "steamcommunity.com"
then there will be a list of IPs (servers) and the ping next to them.
Take best 15 and put to SCM

**Comment by Jentosss** [comment]
Faggots get the fuck out of my knives

**Comment by eLqupe** [comment]
@mtzi thank u. i find another way )

**Comment by Lazko** [comment]
Kann hier jemand deutsch?

Ich hätte gerne eine hostlist aus deutschland

**Comment by donderpate** [comment]
@Alex1os maybe you can share your hosts with us? Or maybe give us some examples? 

i'm from germany too. 

@Lazko ich hatte eine Liste allerdings weiß ich nicht wie effektiv die ist... würde gerne die von alex sehen.

**Comment by Alex1os** [comment]
little update,  I managed to get my dream knife more than once xD now I'm trying some other high tier ones, sadly atm there seem to be extremly many bots searching for those knifes and I didn't get any knife since about a week ago :(

maybe there are faster bots out there who knows^^ or I'm just out of luck xD

Lg Alex

**Comment by donderpate** [comment]
@Alex1os okay this sounds nice. i think the hosts are usefull for me..

@Lazko: Hier ist meine Liste:

88.221.92.17
2.20.182.90
2.20.182.104
92.122.227.97
88.221.77.29
23.62.99.10
2.21.46.13
88.221.92.32
2.18.95.142
2.20.84.153
88.221.211.33
23.14.93.41
2.20.182.67

Ping zwischen 2-40ms
