### ISSUE TITLE
How to change the currency of my scmbot

### ISSUE THREAD

**Issue by kevintj711** [Maxx53/SCMBot#396]
I got a problem with currency 
My local currency of steam market is RP / Indonesian Rupiah
Can someone help me for fix this ? 
Thanks a lot btw :)

**Comment by Maxx53** [comment]
hey bud, check this
https://github.com/Maxx53/SCMBot/issues/225

**Comment by kevintj711** [comment]
can i just change the $ into RP Idr? 
Are these currency only display or its effected the buying price too bro?

**Comment by kevintj711** [comment]
and one more bro can i skip this 7 days of new devices :( this is really waste my 7 days time.

**Comment by Maxx53** [comment]
no, you dammit. 
find **currency code** for your currency and add new line to currency.txt in this format: code,name

for 7-day limit use https://github.com/Maxx53/SCMBot/wiki/Using-Import-Cookie-Tool

**Comment by kevintj711** [comment]
![image](https://cloud.githubusercontent.com/assets/13128689/8539797/e3b745a6-24a9-11e5-932c-2917fd82af3a.png)
i do like that its correct? 

Oh for 7 days its done already thanks dude :)

**Comment by Maxx53** [comment]
no, it's not.
do you know your currency code? 1 is for dollar, 2 is for euro... and for your Rp?
ok. i think, we waste our time, login at http://steamcommunity.com/market/ in your webbrowser and save this page as HTML (ctrl+s) and send me at demmaxx@gmail.com

**Comment by kevintj711** [comment]
oh okayy" thanks wait i sent an email :) thanks a lot bro

**Comment by kevintj711** [comment]
![image](
https://cloud.githubusercontent.com/assets/13128689/8601234/00ed5088-2695-11e5-9d5e-fdeac21c04ec.png
)
The items not yet bought by someone its still in market.
Thats what happen when i put the value already bigger than someone sell it.
i just wanna trying buying something but it cant.
Can someone help me solve this? :)
