### ISSUE TITLE
Just a quick note

### ISSUE THREAD

**Issue by firebug11** [Maxx53/SCMBot#397]
The bot does not see the item if it has a name tag on it, do not know if this is already known. Just thought iwould get it out there :D

**Comment by nux17** [comment]
How could you know that? :P

**Comment by torbalohas** [comment]
![312132](https://cloud.githubusercontent.com/assets/11807150/8571036/fc004034-258c-11e5-890d-ca1902f47377.png)

**Comment by firebug11** [comment]
nux17 I know this because when scanning a item page i can see manually that there is a cheaper price than the bot is displaying and the only reason for that is the name change.
Thanks alot torbalohas, did not see that option :+1:

**Comment by Maxx53** [comment]
well, dat sux
