### ISSUE TITLE
Cant buying using bot 

### ISSUE THREAD

**Issue by kevintj711** [Maxx53/SCMBot#400]
![image](https://cloud.githubusercontent.com/assets/13128689/8601234/00ed5088-2695-11e5-9d5e-fdeac21c04ec.png)
The items not yet bought by someone its still in market.
Thats what happen when i put the value already bigger than someone sell it. i just wanna trying buying something but it cant.
Can someone help me solve this? :)

**Comment by Maxx53** [comment]
lol, upgrade your luck

**Comment by kevintj711** [comment]
Oh no i mean i put the price already more than market price but i still cant buy that using my bot.

**Comment by kevintj711** [comment]
Ah its work now sorry" my bad max XD lol its so embarassed solve thanks!
