### ISSUE TITLE
There was a error purchasing your item.

### ISSUE THREAD

**Issue by kraitfps** [Maxx53/SCMBot#406]
I keep getting this error, I logged with cookies to avoid 7days trade ban.

I'm new btw. Please help me.

edit: When I logged with cookies i let the latest 2 boxes empty because in "importing cookies" tutorial there was no 2 extra boxes so I didnt know what to paste in it.

**Comment by mtzi** [comment]
You need to find  them, they are why u get the problem, need 5 cookies, or "error purchasing item"
You can find them on chrome if u search careful in the cookies

**Comment by kraitfps** [comment]
steamMachineAuth
steamLoginSecure

I really don't know where to find these...

**Comment by mtzi** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12753786/8785928/c9ff0c4a-2f33-11e5-840b-01b23030eed5.png)
 
come on bro.... under steamLogin...

**Comment by kraitfps** [comment]
I'm telling you there's no such thing as steammachine auth/login secure
![scmbott](https://cloud.githubusercontent.com/assets/13423417/8785993/34dd42f2-2f34-11e5-859b-1bf542bd999b.png)

**Comment by mtzi** [comment]
if you have firefox, try that too. i have no idea really... 
try going to your inventory or trades or something...

**Comment by kraitfps** [comment]
Got it with firefox, thanks.

Hope no errors from now on.

**Comment by mtzi** [comment]
normally it should be ok, if u have extra $ buy a polar camo (0.03$) for test

**Comment by kraitfps** [comment]
And what delay is recommanded ? I'm working with only 1 item.

**Comment by mtzi** [comment]
for 1 item? u can go with 1000, if u get errors put it to 1500
i work 6 items 2400 item delay

**Comment by mtzi** [comment]
i hear some ppl have item delay 10, which is too low i think. see what works for you, the lower the better

**Comment by kraitfps** [comment]
Got some with 250 delay, and it's working.

Thank you.
