### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by rnd0m** [Maxx53/SCMBot#417]
постоянно ловится Access Denied сегодня. В свете того, как работает стим последнии дни, и то что прогу я обновил как раз именно сегодня, не знаю, что и думать - то-ли хосты не такие уж бесполезные были, то-ли всё же стим виноват. 
зы: имхо, зря всё таки так с хостами - всё же иметь выбор, как использовать, лучше, чем не иметь )

**Comment by Maxx53** [comment]
хосты оставлены, их польза подтверждена

**Comment by rnd0m** [comment]
о, спасибо. всё время забываю проверить новую версию, прежде чем писать что-то ). извиняюсь
