### ISSUE TITLE
Cannot sell cards?

### ISSUE THREAD

**Issue by xYaro** [Maxx53/SCMBot#450]
![Picture](https://cloud.githubusercontent.com/assets/14079198/9612400/1d9112fc-50ab-11e5-9953-f4a467e0edc3.png)

http://pastebin.com/1nZfW02Y

It used to work, until about a month ago and it stopped. I reinstalled Windows several times (not related to this) but it still happens.

**Comment by Maxx53** [comment]
watta fuck in your cost column? remove currency
http://www.youtube.com/watch?v=gehs3T8B4os

**Comment by xYaro** [comment]
It was set like that automatically, but when I remove it, it sets the "you receive". However it still doesn't work. Same error.
