### ISSUE TITLE
Unlocked courriers (question)

### ISSUE THREAD

**Issue by Cashmaker** [Maxx53/SCMBot#453]
Can i set the bot to specifically buy unlocked courriers like Pudgling with golden hook for exemple?

**Comment by mtzi** [comment]
if you can make it happen in normal page of market, you copy that link, and paste it up left on bot where it keeps destination link "link to items"
but you have to be sure you copy the correct link from steamcommunity market first

**Comment by Cashmaker** [comment]
Okay, and how do i find the link for the unlocked courrier and not the locked ones ?

**Comment by mtzi** [comment]
you have to make it, steam market has a "filter results" thing, if you can make it show ONLY upgraded you are good to go, im not sure how to, sorry

![capture](https://cloud.githubusercontent.com/assets/12753786/9694564/727e70a2-5362-11e5-9c3d-d4a118586d61.PNG)


See pic, here is what i say, what i wrote DOESNT work, still shows all, you have to find HOW TO SHOW ONLY GOLD
then take the link up (which changes if u search) and paste in bot

**Comment by Cashmaker** [comment]
I got you, i'm gonna try to find if there's a way to only show the unlocked ones. I'll post back soon if it worked or not

**Comment by mtzi** [comment]
you can use search identifiers like google ( NOT , OR , AND ), these might be useful, work only in full caps eg NOT locked or shit

**Comment by Cashmaker** [comment]
Thanks

You had to type it this way

pudgling NOT locked

Exemple here
http://steamcommunity.com/market/search?appid=570&q=pudgling+NOT+locked

**Comment by mtzi** [comment]
thanks, even though im not gonna use it, and you shouldnt share info like this to others to bot same things as you.
GL man
