### ISSUE TITLE
Задержка перед ошибкой.

### ISSUE THREAD

**Issue by Justmau5** [Maxx53/SCMBot#484]
Задержка на предмете 500, максимум одновременных запросов 1, задержка между запросами 0.
Хостов много, пинг 2-3 ms. Программа сканирует стабильно каждые 1-2 секунды, но как появляется возможность покупки идет большая задержка, после которой идет ошибка "Не удалось купить данный предмет..." 
Такая ошибка была и до обновления стима, так что думаю проблема не только в нем.
![62a8f686-75bb-11e5-8ac2-dd5cf5131477](https://cloud.githubusercontent.com/assets/13572267/10564466/0c80c83a-75be-11e5-854c-d164abdd9fc6.PNG)

**Comment by Justmau5** [comment]
Сделал задержку в 100, что бы было более наглядно,
![default](https://cloud.githubusercontent.com/assets/13572267/10564478/5370130e-75be-11e5-9310-f7a6153fbb25.PNG)

**Comment by Jiqus** [comment]
поддерживаю

**Comment by Maxx53** [comment]
что я могу сказать, так стиме реализована покупка. попробуй что-нибудь купить в браузере, аналогично, на 5-10 секунд стим "задумается".
почему возникает ошибка. один предмет одновременно пытаются купить несколько человек. соответственно, сервер может продать предмет только одному, остальным возвращает ошибку "приобрел другой".
разве это не очевидно?

**Comment by Justmau5** [comment]
@Maxx53 Естественно очевидно что покупка не совершается сразу, это и ежу понятно, дело тут в другом. Раньше такого не было, такая ошибка возникала очень редко, поэтому все люди начали волноваться.

**Comment by Justmau5** [comment]
@Maxx53 тем более учитывая мои настройки и хосты, ну кто может быть быстрее этого?

**Comment by X4ndrius** [comment]
@Maxx53 Макс. Тут речь не о том что сама ошибка появляется. А о том что программа долго задумывается при ее выводе. Покупка кстати выводится практически моментально.

**Comment by Justmau5** [comment]
С выводом в продажу вообще проблем нет

**Comment by Maxx53** [comment]
почему программа "задумывается"? ждет ответа сервера.
почему сервер не торопится отвечать? тайна. возможно, сервер собирает список желающих, а мексиканские дети с завязанными глазами тыкают в него пальцем. на чье имя палец встанет, тому и продают.

**Comment by Jiqus** [comment]
:)

**Comment by Justmau5** [comment]
@Maxx53 Мексиканские мальчики какие то не те стали, они предали нас, они тыкают не в тех людей.

**Comment by Maxx53** [comment]
как вариант - скрытая группировка, использующая, хаки, уязвимости или даже поддержку самой вэлв. вот они и перехватывают все выгодные покупки.
но это уже близко к теории заговора.

**Comment by Justmau5** [comment]
@Maxx53 Стоит ли искать в твоих сообщениях скрытый смысл? И раз уж ты начал желание допила программы в чем дело? дело в желании или в деньгах?

**Comment by Exstasy** [comment]
Лови подачу от Стима 50 запросов за 2 мин бан на весь день!!!

**Comment by Justmau5** [comment]
@

**Comment by X4ndrius** [comment]
@Exstasy Тоже заметил. Но врядли 50 запросов за 120000ms. Наверняка чаще запросы шли.
