### ISSUE TITLE
non ban settings !!!

### ISSUE THREAD

**Issue by dantrus87** [Maxx53/SCMBot#504]
2 дня уже тестю программу, нашел оптимальные настройки , при которых можно сканить 2-3 вещи на 1 компе практически без банов.

requests limit / количество запросов  1-2
delay between rquests / задержка между запросами 2500 ms
UnBanInterval  1800000 (30 min)  =1 item ;    3600000 (60 min) =2 item
и очень важно ставить хосты из разных мест: Европа, Сша, тогда шансы бана уменьшаются.
hosts:
23.202.195.235
23.203.166.124
172.231.225.211
23.32.163.235
190.124.166.126
23.218.108.113
172.229.237.100
23.193.162.112
23.78.179.235
23.78.246.124
23.218.138.226
172.232.215.155
96.16.160.52
69.192.62.208
23.49.62.112
172.232.38.124
23.196.180.116
96.17.83.235
23.196.4.112
184.31.120.26
23.0.51.235
23.37.0.192
172.232.9.175
23.203.16.192
23.219.224.230

Тестируйте, отписывайте у кого как, давайте решим проблему вместе. Спасибо;)

**Comment by Rocky54** [comment]
Мы получем бан, ждём 1-2 минуты и он пропадает. Ботим-ботим и опять получаем, и опять ждём. И он опять спадает. НО в конце концов он не проходит через минуту. И получаем мы его на 4 - 12 часов. У меня он может работать 2-3 часа с 1 минутным баном.

**Comment by dantrus87** [comment]
Да, тоже самое с самого начала было, нужно задержку ставить больше, лучше её поставить больше но не получить бан на 12 часов, вот такое у меня мнение.

**Comment by Rocky54** [comment]
@dantrus87 

Фигня какая то... А не настройки.

Ты сам посуди. Интервал бана - 30мин. То есть 30минут бот не будет работать. А я эти мини баны получаю каждые 15-20мин. У меня он стоит полторы минуты. То есть я получил, полторы минуты не поработал и потом опять 20мин спокойно работает. Задержка 2500 это в настройках? Если да, то у меня там 500 а на предмете 1500

**Comment by dantrus87** [comment]
у тебя 1 предмет на 1 компьютер? если да, то настройки подойдут для 1 предмета, а для более бан скорее всего влепят:/

**Comment by nikita971** [comment]
спс, вроде норм скан идет, посмотрим что будет ночью

**Comment by Rocky54** [comment]
@dantrus87 
ДА, 1

**Comment by Rocky54** [comment]
@dantrus87 

Скорее всего с твоими настройками и 100 р не сделаешь в день с 1 предмета

**Comment by kyotooo** [comment]
![kk](https://cloud.githubusercontent.com/assets/15572119/10870191/d085643a-80d5-11e5-9e90-242f1cd9afc7.jpg)
С данного ип адреса(это дедик) - установлен прокси сервер. С которого данный человек ловит ваши запросы. Человек, как вы поняли - русский.

Суть - человек ловит запросы, получая ваши coockies - тем самым без проблем может через браузер зайти в аккаунт. Но у него возникли небольшие проблемы - не может поймать SteamMachineAuth - тем самым просит всех в другой теме копировать coockies через импорт.
