### ISSUE TITLE
hosts.txt

### ISSUE THREAD

**Issue by Johannson** [Maxx53/SCMBot#506]
Hello guyz, I found a lot of hosts of steamcommunity, maybe it can help you with ban problems.
81.94.157.171
184.31.141.210
23.206.211.235
190.124.166.126
23.204.141.210
23.204.248.238
23.203.199.191
184.85.53.109
23.202.195.235
23.203.166.124
172.231.225.211
23.32.163.235
184.25.118.112
23.192.124.247
23.218.108.113
184.30.182.170
184.50.3.17
23.41.161.9
23.74.14.112
184.31.232.116
23.47.183.5
23.52.141.210
172.230.101.79
23.211.113.110
96.7.94.208
184.27.37.253
23.210.223.211
23.3.16.192
184.25.142.208
184.85.160.192
23.211.4.172
184.26.61.110
172.229.135.190
23.193.13.210
96.6.110.208
69.192.35.235
2.16.110.247
96.6.227.235
23.5.231.6
23.200.228.116
23.10.128.192
23.13.147.235
23.203.58.247
23.192.109.210
172.230.227.169
172.229.237.100
23.193.162.112
23.78.179.235
23.78.246.124
23.218.138.226
172.232.215.155
23.196.100.212
23.66.195.235
23.206.150.124
23.209.102.124
23.60.13.210
96.16.160.52
23.202.230.112
173.222.43.212
172.231.28.78
69.192.62.208
23.49.62.112
172.232.38.124
23.196.180.116
96.17.83.235
23.196.4.112
184.31.120.26
23.0.51.235
23.209.61.210
23.37.0.192
172.232.9.175
23.203.16.192
23.219.224.230
23.212.9.13
96.7.168.116
23.0.0.192
23.220.51.28
104.64.48.98
23.213.61.54
172.231.48.97
184.26.40.112
172.230.110.112
23.38.72.41
23.7.199.225
2.17.35.235
172.229.200.45
2.16.88.247
95.100.69.109
2.20.152.41
84.53.167.235
184.25.216.60
23.214.102.85
23.2.176.97
23.10.176.192
23.44.112.230
23.76.208.192
184.24.190.208
172.232.72.102
23.47.7.225
184.50.163.235
23.214.146.125
23.196.8.112
172.232.108.232
23.49.240.230
184.84.128.192
184.26.50.112
23.212.173.210
173.223.126.208
23.9.247.191
23.0.19.235
23.4.199.225
23.76.104.112
23.49.60.112
23.1.235.55

**Comment by Exstasy** [comment]
@Johannson  THX

**Comment by Oaaa** [comment]
you also can go to https://asm.ca.com/en/ping.php and type in http://steamcommunity.com/market/ and take the ips that are listed on there next to the countrys you are close to.

**Comment by mindflare** [comment]
hi guys, sorry i dont really understand. Does this really help from getting "too many request" error? because i thought they triggered the ban based on your router's ip address?

**Comment by Oaaa** [comment]
@mindflare i dont think that helps for the bans, but you can bypass this by simply writing a makro to reset your router/vpn every 30 minutes so u will never get banned.

these ips only help you to get the best connection to the steam market server so you are able to buy items faster than other people. it acutually just gives you more income with the same ammount of requests.

**Comment by mindflare** [comment]
@Oaaa oh ic thanks.

**Comment by Oaaa** [comment]
@mindflare do u have a bot that is running?

**Comment by mindflare** [comment]
nope, my router does not supports resetting of public ip address even though i off it and turn it back on after 30minutes; its a static ip so i have to call my isp to do it on their end but not a very wise solution.

**Comment by Oaaa** [comment]
@mindflare just juse a vpn to a server next to your location. u will get like 3 more ms and u can reset the ip whenever you want

**Comment by mindflare** [comment]
@Oaaa haha vpn have to pay or else only have limited data usage.

Just wondering, if i were to use back the cookie file i saved locally, will i face with steam guard error because the location is different and currency will change? assuming that vpn server is located in US and i'm in asia. Do i have to perform a new login and access my email for the new steam guard code?

**Comment by Oaaa** [comment]
@mindflare i live in pattaya and i can make a proxy to bkk for free.
i dont think u will have a problem finding a free proxy for your location that will work just fine.

if you live in asia and use a vpn to the us and then use an ip for the us steam market servers, you will have a ping around the 300 ms. that is really bad and u wont be able to buy a lot.
what u want is a vpn that connects with the next location to your home, and u only use ips for steam martket servers in your area.

i am located in thailand and i got these connections:
http://fs5.directupload.net/images/151027/j4crld5l.jpg

if i would now use a vpn to the usa and then connect to the usa steam market servers i would have about 250ms - 300ms from my home to the proxy and then another 2ms - 30ms to the servers. yes, there are more steam market servers in the us/europe, but if you use your bot with 250ms, all the other bots with 10ms - 30ms will buy all the items faster than you.

**Comment by mindflare** [comment]
@oaaa Lol seems like proxy servers are fully utilised for steam bots, i keep getting error 429 too many request haha

**Comment by Oaaa** [comment]
error for too many requests within a short period or a timed ban for your ip because you make too many requests within an hour?

**Comment by kyotooo** [comment]
![kk](https://cloud.githubusercontent.com/assets/15572119/10870191/d085643a-80d5-11e5-9e90-242f1cd9afc7.jpg)
Не советую использовать все хосты, особенно 190.124.166.126.
С данного ип адреса(это дедик) - установлен прокси сервер. С которого данный человек ловит ваши запросы. Человек, как вы поняли - русский.

Суть - человек ловит запросы, получая ваши coockies - тем самым без проблем может через браузер зайти в аккаунт. Но у него возникли небольшие проблемы - не может поймать SteamMachineAuth - тем самым просит всех в другой теме копировать coockies через импорт.
