### ISSUE TITLE
"Error parsing search results"- How do i fix this??

### ISSUE THREAD

**Issue by TheNoobster8** [Maxx53/SCMBot#507]
Initially using the bot, it ran beautifully for the first 10-15mins. Then suddenly it stopped searching for items. Every time I clicked search, it gave me the error message: 

"Error parsing seach results."

Because of that error, it basically won't let me use the bot. If anyone knows the fix to this or why this is happening PLEASE reply. 

Also, if anyone knows how to stop steam from thinking some1 else is using your steam account (then they send you an email verification...etc.) lmk as well!

Thanks, hope you can help and have a great day!

**Comment by Exstasy** [comment]
steam rip

**Comment by TheNoobster8** [comment]
?

**Comment by TheNoobster8** [comment]
what do you mean?
