### ISSUE TITLE
CoockieContainer issue

### ISSUE THREAD

**Issue by immorro** [Maxx53/SCMBot#510]
Не смог докопаться до истины в твоем проекте...как ты хранишь значения кукисов?
Value, содержащее запятую, в CoockieContainer никак не влазит - доки говорят, что это невозможно. Как тогда создать CoockieContainer из строки? 

//System.Net.CookieException: Недопустимая часть "Value"="7200,0" файла cookie.

**Comment by mindflare** [comment]
try removing the timezoneOffset property.

**Comment by immorro** [comment]
This solved the problem:
Name = HttpUtility.UrlEncode(name),
Value = HttpUtility.UrlEncode(value),
