### ISSUE TITLE
How to input your hosts?

### ISSUE THREAD

**Issue by TheNoobster8** [Maxx53/SCMBot#512]
I have a bunch of hosts that connect to the steam community, but how do i actually input them into SCM Bot? 

Sorry for the newbie question :P 

Also, if my internet comes from a router, how can i change my ip, isn't it static?

Thanks, and have a great day guys!

**Comment by mindflare** [comment]
replaced it in your hosts.txt file
example: https://github.com/Maxx53/SCMBot/blob/master/scr/SCMBot/hosts.txt

Not sure whether your ip address is static. try to turn off your router, wait for few minutes and turn back on.
