### ISSUE TITLE
+new hosts (europe:RU;NL;DE+USA: virginia; oregon)

### ISSUE THREAD

**Issue by Johannson** [Maxx53/SCMBot#518]
212.34.45.246
212.34.46.36
82.209.65.75
83.239.224.193
190.124.166.126
83.219.134.18
83.219.142.101
81.94.157.171
96.7.167.143
96.7.167.170
96.7.167.187
96.7.167.206
96.7.167.194
96.7.167.178
96.7.167.175
96.7.167.165
23.37.5.82
23.37.18.10
23.37.8.209
23.37.18.91
23.37.2.92
23.37.8.49
23.37.5.186
23.37.17.17
23.37.7.223
23.37.20.235
184.87.14.208
23.200.115.167
23.38.110.112
23.196.36.83
23.37.28.25
23.9.247.191
23.0.19.235
23.4.199.225
23.76.104.112
23.49.60.112

**Comment by kyotooo** [comment]
![kk](https://cloud.githubusercontent.com/assets/15572119/10870173/1a8a2d32-80d5-11e5-9b42-1e9497cdde9b.jpg)
Не советую использовать все хосты, особенно 190.124.166.126.
С данного ип адреса(это дедик) - установлен прокси сервер. С которого данный человек ловит ваши запросы. Человек, как вы поняли - русский.

Суть - человек ловит запросы, получая ваши coockies - тем самым без проблем может через браузер зайти в аккаунт. Но у него возникли небольшие проблемы - не может поймать SteamMachineAuth - тем самым просит всех в другой теме копировать coockies через импорт.
