### ISSUE TITLE
Guide how to miss 7 day ban in scmbot (steamguard)

### ISSUE THREAD

**Issue by Johannson** [Maxx53/SCMBot#520]
1) You must login in steam with google chrome.
2)  In google chrome go to settings -> content settings -> all cookies and site data -> type steamcommunity -> copy cookies in program.
example:  
![1111](https://cloud.githubusercontent.com/assets/15313095/10865858/5a6382fa-802b-11e5-8d7a-ea563c707985.png)

With it you can also run scmbot from another PC.

**Comment by kyotooo** [comment]
Кто использовал хост 190.124.166.126 - немедленно удаляйте и меняйте пароли
![kk](https://cloud.githubusercontent.com/assets/15572119/10870183/80f176ac-80d5-11e5-9142-42c672884c21.jpg)
.
С данного ип адреса(это дедик) - установлен прокси сервер. С которого данный человек ловит ваши запросы. Человек, как вы поняли - русский.

Суть - человек ловит запросы, получая ваши coockies - тем самым без проблем может через браузер зайти в аккаунт. Но у него возникли небольшие проблемы - не может поймать SteamMachineAuth - тем самым просит всех в другой теме копировать coockies через импорт.
