### ISSUE TITLE
hosts.txt

### ISSUE THREAD

**Issue by init92** [Maxx53/SCMBot#525]
81.94.157.171
212.34.45.246
212.34.46.36
82.209.65.75
83.239.224.193
83.219.134.18
83.219.142.101
23.202.195.235
23.203.166.124
172.231.225.211
23.32.163.235
23.218.108.113
172.229.237.100
23.193.162.112
23.78.179.235
23.78.246.124
23.218.138.226
172.232.215.155
96.16.160.52
69.192.62.208
23.49.62.112
172.232.38.124
23.196.180.116
96.17.83.235
23.196.4.112
184.31.120.26
23.0.51.235
23.37.0.192
172.232.9.175
23.203.16.192
23.219.224.230

**Comment by greenberg3** [comment]
and?
