### ISSUE TITLE
Sticker check

### ISSUE THREAD

**Issue by deathes** [Maxx53/SCMBot#538]
Can you/we implement a simple code to check if a given item has any sticker on it or not? It would be nice to only buy an item at a given price if there's a sticker on it.

**Comment by mtzi** [comment]
go to market, filter results, copy URL link (it changes, adds something like ?filter=sticker or smth in the end), paste it to bot "URL" under "item name"
it has beed there forever

**Comment by deathes** [comment]
Thanks for the tip :)
