### ISSUE TITLE
Рандомная задержка. 

### ISSUE THREAD

**Issue by Justmau5** [Maxx53/SCMBot#545]
Один господин уже пытался добавить данную фичу https://github.com/Maxx53/SCMBot/pull/185
ну судя по всему он ее не совсем правильно реализовал, можно ли ее реализовать как нибудь в обнове? (если она вообще будет). А так же можно добавить что-то типа таймера работы, то есть что бы можно было указывать в настройках время работы и паузы после нее. Пытался сам собрать, но с моим уровнем программирования я все только сломал :D

**Comment by Justmau5** [comment]
up? @Maxx53 ты бы хоть отписал что думаешь

**Comment by Maxx53** [comment]
ничего не думаю, рандомная задержка даже теоретически - полная хрень. ее эффективность вообще на практике проверена?

**Comment by Justmau5** [comment]
@Maxx53 я опираюсь на отзывы "конкурентов" у которых появилась данная функция, а что по поводу таймера работы?
