### ISSUE TITLE
[Q] Does account needs CS:GO in library to buy items ?

### ISSUE THREAD

**Issue by mapex39** [Maxx53/SCMBot#546]
If we dont need to buy game to buy items on scm its gonna be great.

**Comment by mtzi** [comment]
im pretty sure u need the game first

**Comment by Maxx53** [comment]
not really.

**Comment by mapex39** [comment]
@Maxx53 Can you say something more?

**Comment by Oaaa** [comment]
u can buy any item in the market no matter if u have the game or not!
