### ISSUE TITLE
Is a vps worth it?

### ISSUE THREAD

**Issue by Alex1os** [Maxx53/SCMBot#554]
Hello again

Sicne I've been using the scm bot for quiet some time now I was thinking about upgrading my "botting experience" with a server. Since vps cost very much I would like to know if it is worth it vs home server/pc with broadband internet. (note I have around 7-11ms ping on steamcommunity.com server)

I would like to test the scm bot on a vps but I havn't found anyone who could help me...

thanks in advance

Alex

**Comment by LawrenceCSGO** [comment]
So what's the question? If you're using your home server quite succsessfully, why do you need a VPS at all?

**Comment by Alex1os** [comment]
@LawrenceCSGO 
I didn't say I am successful. Tbh I didn't get a good knife in the last 4 months.

I am just looking for someone who has already done scm bot with vps before and share some knowledge...

Alex

**Comment by LawrenceCSGO** [comment]
Well, there are different methods to use bot: a simple home one-threaded setup with hosts, multiple bots with proxies, virtual machines with VPN connections — yours or bought ones.
The main question depends — with simple home using you need to have a fast ping to their servers, with multiple bots you need fast proxies with the same good ping. I think VPS is for these who can't afford all this — a good connection to Valve servers, a 24/7 working PC at home, a stable and good Internet connection.
