### ISSUE TITLE
Уведомление о бане. 

### ISSUE THREAD

**Issue by Justmau5** [Maxx53/SCMBot#557]
Я думаю это будет полезно для людей у которых организован ботнет или для тех, кто не может постоянно мониторить работу бота. Рассылку можно сделать в виде сообщения по почте, отправленное самому себе, ну это только первая мысль, можно как то иначе.

**Comment by rnd0m** [comment]
ну а для тех, у кого нет ботнета, пригодилось бы хотя б звуковое оповещение об этом самом бане )

**Comment by OlegarhViktorio** [comment]
Если нужно звуковое оповещение, то добавьте одну строчку в код и перекомпилируйте

                case "9": mess = "Got Banned! Waiting for UnBan...";
                    Console.Beep(1000, 5000);
                    break;

Можно туда и рассылку запихать.

**Comment by rnd0m** [comment]
@OlegarhViktorio, спасибо
