### ISSUE TITLE
new hosts (03.12.2015)

### ISSUE THREAD

**Issue by init92** [Maxx53/SCMBot#558]
23.32.163.235
81.94.157.172
23.218.108.113
172.229.237.100
23.193.162.112
23.78.179.235
23.78.246.124
23.218.138.226
172.232.215.155
96.16.160.52
69.192.62.208
23.49.62.112
172.232.38.124
23.196.180.116
96.17.83.235
23.196.4.112
184.31.120.26
23.0.51.235
23.37.0.192
172.232.9.175
23.203.16.192
23.219.224.230

**Comment by OlegarhViktorio** [comment]
Опять это х**ло свои паленые хосты сюда бросает?
