### ISSUE TITLE
Discount probs?

### ISSUE THREAD

**Issue by utka1** [Maxx53/SCMBot#568]
SCMbot&STH are not both working if i want to purchase smth.

"There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again."

can it be caused by discount, and what should i do to continue using it? thx

**Comment by immorro** [comment]
try
https://github.com/Maxx53/SCMBot/issues/549

**Comment by utka1** [comment]
@immorro спс, осталось научиться компилировать

**Comment by immorro** [comment]
https://github.com/Maxx53/SCMBot/issues/549#issuecomment-160313449
