### ISSUE TITLE
Wallet Max Amount

### ISSUE THREAD

**Issue by VNnaD** [Maxx53/SCMBot#603]
I know on USD max amount its 500$ and EUR its 450€
Then how is it possible to create a buy order higher then your max steam wallet ? 
http://imgur.com/54a048z
http://imgur.com/JAEngAe

**Comment by utka1** [comment]
Who knows?

**Comment by mtzi** [comment]
Russian currency, Hindu currency, and generally ANY unstable currency. 
Eg. Euro last night 5/2 was on 1$ - 0.92Euro, so max wallet 500$ -> 460Euro, today its 1-0.9, so max is 450Euro
Imagine that when a currency drops, eg the hindu one, u can add 500$ that will become MORE than 500$ when the currency goes back up,
Eg, i put 460Euro last night, so today with new currency stats i have 511$ in wallet, meaning i can outbuy americans etc

**Comment by VNnaD** [comment]
@mtzi Ok thx
