### ISSUE TITLE
Got Banned! Waiting for Unban...

### ISSUE THREAD

**Issue by steamflux** [Maxx53/SCMBot#611]
Is there any way to avoid this "Got Banned! Waiting for Unban..." thing? I kept on receiving that message while I'm using the bot, any idea to avoid it please? Or is it the new system of Steam to avoid bots on spamming some request? Ty

**Comment by Maxx53** [comment]
https://github.com/Maxx53/SCMBot/issues/493
well

**Comment by steamflux** [comment]
I cant understand russian language,  btw,  do I need to download that scmbot-test.rar?

**Comment by Maxx53** [comment]
use google translate maybe?
btw, yes, it is feature to stop scanning while your IP getting ban

**Comment by steamflux** [comment]
So there's no way to stop that waiting for unban thing?  Is it natural to receive that message since bot kept in spamming request so the steam server wil block my ip?

**Comment by Maxx53** [comment]
yis, you're right

**Comment by steamflux** [comment]
It means I need to use VPN able to start scanning prices again?

**Comment by Maxx53** [comment]
not really, ip ban is temporary, just wait for unban.

**Comment by steamflux** [comment]
Yea,  but  I waited like 14h before to unban, Im not sure about when it will be unban, so do you know when will be my ip get unban?
