### ISSUE TITLE
Еще об SCMBot alpfa 2

### ISSUE THREAD

**Issue by Validius** [Maxx53/SCMBot#614]
Макс, бот очень важен и нужен.

Пользуюсь пока предыдущей версией, просто как списком предметов с ценами покупки и продажи.
В новом боте не устраивают два момента.
1. Список хотелось бы стационарный, чтоб предметы по закрытии ордера не удалялись, а просто изменялся статус ордера (как было раньше).
Если много предметов, то очень не удобно искать потом, какие закрылись. Да и по-порядку чтоб все время не менялись позициями.
2. Автопродажа выставляет предметы только после покупки всех предметов (закрытии позиции), а хотелось бы чтоб сразу после покупки каждого. И счетчик количества обновляется по всем предметам аналогично - только когда закрывается одна из позиций.

Макс, чуть чуть WM кинул, будет еще.

Возможно ли это реализовать и когда можно ждать патча?

**Comment by Maxx53** [comment]
не надо плодить темы. альфу 2 обсуждаем только здесь https://github.com/Maxx53/SCMBot/issues/599
