### ISSUE TITLE
Read about the new security requirements coming to the Community Market on March 9th. 

### ISSUE THREAD

**Issue by recfunc** [Maxx53/SCMBot#616]
Читали? Теперь каждый листинг нужно будет подтверждать мобильником?

**Comment by utka1** [comment]
@recfunc 
не знать англ в 2016
там написано, что для тех кто еще не привязал телефон(аутентификацию с него то бишь), будет действовать задержка вещей - ты как бы купил вещь, а выставить можешь через 15 дней(или там с момента выставления на тп 15 дней пройти должно, не помню уже сейчас)
такие дела.

**Comment by recfunc** [comment]
@utka1 
Ну раз такое дело, то советую к прочтению http://store.steampowered.com/mobile/

**Comment by Exstasy** [comment]
Ничего удивительного. Лучше бы в доте ограничение сняли с этим аутефикатором саным и кс в добавок. Все равно это обходится на изи...

**Comment by recfunc** [comment]
> Все равно это обходится на изи...

Что именно?

**Comment by utka1** [comment]
@recfunc 
Not all Market listings will require confirmation, most listings under $3.00 USD can be posted immediately.

A delay to catch and stop item theft
If a user trading away or selling items hasn't had their account protected by a Mobile Authenticator for the past 7 days: 
Trades: item delivery from completed trades will be delayed by Steam for up to 3 days 
Market: starting March 9th, sell listings will be held by Steam before they are posted, for up to 15 days

**Comment by recfunc** [comment]
> $3.00 USD

А что будет с листингами, ниже чем 3 доллара без мобильной аутентификции? Они будут задерживаться на 15 дней или нет? Это слегка не понятно мне.

**Comment by Exstasy** [comment]
@recfunc по моему там все будет задержано независимо от цены.

**Comment by Exstasy** [comment]
@recfunc даже если не будет. Карл 15 дней обмен ждать. 15 дней ебана рот это 2 раза в месяц можно шмот вывести. Короче пошел ставить аутефикаторы на машины

**Comment by Exstasy** [comment]
Иначе хрен шмота куплю на вывод...

**Comment by recfunc** [comment]
@Exstasy 
Вообще, если удастся декомпилировать steam mobile app, можно эмулятор написать.

**Comment by MazaFaker** [comment]
@recfunc  Что-то типо этого ? http://i.imgur.com/fSHcisi.png

**Comment by MazaFaker** [comment]
@recfunc ! [fshcisi](https://cloud.githubusercontent.com/assets/15183784/13471002/cbfa2fd2-e0bf-11e5-9bb3-2769b6c58179.png)

**Comment by recfunc** [comment]
@MazaFaker 
Нет конечно, гуйня пустая трата времени.
Должен быть кросплатформенный демон с любым межпроцессорным взаимодействием, будь то dbus, сокеты, либо еще что-то.

**Comment by MazaFaker** [comment]
@recfunc Щас бы нести хуйню пытаясь выглядеть умным, ну давай, создавай велосипед, удачи

**Comment by recfunc** [comment]
@MazaFaker 
Что?

**Comment by MazaFaker** [comment]
@recfunc  Какое отношение имеет вышесказанная тобой хуета к обычному эмулятору мобильного приложения ? Если тебе надо пояснять, то: под "создавай велосипед" я имел ввиду, что то что ты хочешь создать уже давным давно есть в просторах интернета

**Comment by recfunc** [comment]
@MazaFaker 
Это не хуйня, так должно выглядеть нормальное приложение, а не то, что ты выше показал.
Что ты выше показал у него применений ноль, как я уже сказал - пустая трата времени. т.к. этот функционал реализуется любым софтом для запуска андройд приложений.

**Comment by MazaFaker** [comment]
@recfunc А что в твоем понимании должно делать мобильное приложение steam, помимо гвард ключа и подтверждений на обмен и выставление предметов ( при желании можно автоматизировать, чтобы лишний раз не заходить в само приложение ) ?

**Comment by recfunc** [comment]
Тоже самое, но оно должно запускатся в теории хоть на винде, хоть на линуксе, хоть на осх. Ну и оповещать другие приложения каким-либо способом.
Да и гуйня - сомнительная фишка, на серверах уже не запустишь. Тут либо пилить 2 версии + либу, либо просто консольное приложение, что во многом лучше.

**Comment by MazaFaker** [comment]
@recfunc Я тебе еще раз говорю, не пытайся выглядеть умным, то что ты говоришь - бессмысленная и лишняя хуета, к чему мне запускать на всех ОС, если я пользуюсь только Windows (в моем случае), все функции нужные для ботоводства она спокойно выполняет, так же на удаленных серверах. К чему весь этот бред, который ты пытаешься донести ?

**Comment by recfunc** [comment]
Если это бред - не слушай и не отвечай. К чему ты отвечаешь? Ты патаешься меня переубедить в моих суждениях? Не к чему это.

**Comment by MazaFaker** [comment]
@recfunc Просто мне не нравятся такие люди как ты, которые зная что они не правы, все равно выкручиваются и пытаются доказать свою правоту. Ты написал, что нужно декомпилировать steam mobile app, чтобы написать приложение для пк, я тебе показал, что такое приложение уже существует и прекрасно выполняет все нужные функции. Ты все так же продолжаешь нести хуйню, пытаясь доказать что это не то что нужно.

**Comment by recfunc** [comment]
@MazaFaker 
Ничего ты не знаешь, сынок.

**Comment by MazaFaker** [comment]
@recfunc Аргументный аргумент

**Comment by recfunc** [comment]
@MazaFaker 
Иди погугли сколько vds с виндой в месяц стоит. Представь что у тебя около 10 учеток с ботами(у кого-то и больше) и приходи обратно.

**Comment by MazaFaker** [comment]
@recfunc А то что у меня было 39 дедиков на которых были установлены боты, не учитывать ?

**Comment by MazaFaker** [comment]
На данный момент работают 17 учеток с ботами и на каждом установлено именно то приложение со скрина, которое выполняет все нужные мне функции. Видимо ты ничего не знаешь, сынок

**Comment by recfunc** [comment]
> дедиков

Ну и что это за жаргон непонятный?
Предположим это сервера с виндой. Кстати, что на счет доп. ip андресов не знаю... Ну не суть.
т.е. смотри у тебя было 39 ботов ~20 000 - 30 000 руб. чистыми с каждого в месяц(при алгоритме просмотра выбранных товаров). Итого 975 000 руб в месяц. Да ты ж  миллион в месяц зарабатываешь!

**Comment by MazaFaker** [comment]
Virtual Dedicateted Servers (VDS) - Дедик

**Comment by MazaFaker** [comment]
@recfunc Были времена, доходило до 500к чистыми в месяц, до обновления в стиме, сейчас же занят другим делом, который на много выгоднее

**Comment by recfunc** [comment]
Обманываешь ты нас, ой как не хорошо...

**Comment by MazaFaker** [comment]
@recfunc  И к чему ты удивляешься на 39 ботов, у Exstazy к примеру было около 80

**Comment by MazaFaker** [comment]
@recfunc Я не сомневался, что для тебя не поверить - будет единственным выходом

**Comment by Exstasy** [comment]
@MazaFaker было и будет) Софт уже делают=) Ща пока ставочки.. Если кому интересно вот вам источник дохода со ставок chrome-extension://ghahcnmfjfckcedfajbhekgknjdplfcl/settings/index.html
Все просто ищем шмот который оценивается дороже закупаем тыс на 10-100 через неделю ставим с 2х 10 акк туда сюда и разница будет наш плюс. либо на 1 команду заряжаем тогда профит будет ахуевшим... Тут тупо на ставках можно фармить как в былые времена по 500-1500к )))) В доте такой же абуз есть но надо рыскать шмотки. Можно будет еще попробовать стимулирование цен в стиме. Муторно зато прибыль каласальная. уже наверно предпологают как это делать. Я на треше пробовал вроде работает, на дорогих хз. Хотя если иметь баланс 500к в стиме можно его нагнуть на некоторых лотах) Профит будет очень огромный

**Comment by Exstasy** [comment]
chrome-extension://ghahcnmfjfckcedfajbhekgknjdplfcl/settings/index.html

**Comment by Exstasy** [comment]
Еще есть тема нормальная тоже со ставками связана но тут нужен софт ибо вручную ахуеешь делать. Допустим закупаем 1000-3000 шмоток по 10р которые оцениваются как 25р. передаем их по акк по 40-80штук ждем матчи где высокая вероятность захода изи коэфа. кфц 3-5 и ставим. в итоге профит будет заключаться в том что когда у нас в алуе 3-4 бакса нам дают всякую муть которая чуть ли не дороже стима стоит. В итоге если у вас с математикой не все плохо. Считаем 1 ставка затраты 40р а то и меньше. 100 ставок это 4000р. и тут уже все зависит от кфц допустим кфц 2 профит с 1 ставки 1.85$ это где то 140р-155р то есть с 100 ставок будет профит 14000-15000р. Теперь считаем наш профит допустим мы выйграли 15к. Потратили 4к. Суть в том что если купить нож за 4к и поставить на кфц 2 нам дадут этот же нож  + хуйню какую нить в итоге мы якобы выйграем 8к но вы хуй продадите нож 1-1. сразу -30% убирайте. в итоге вы получите 5500-6000 макс с продажи. А если выводить треш вы теряете 5-10% в итоге профит просто огромный. Но тут нужен софт. Но если все реализовать можно на ставках поднимать по 30-100к в день не че не хуя не делая. нужно только ждать матчи бо1 где все 50-50 а кфц сладенькие.

**Comment by Ignat0ff** [comment]
@Exstasy Если можешь рассказать по подробнее про эту тему , стучи в скайп : ignatnevinovat .

**Comment by qwert1223** [comment]
Как вы задолбали писать тут всякую херню, особено Exstasy  это пиздец)

**Comment by recfunc** [comment]
Таки да, оно требует подтверждения для каждого листинга.

**Comment by Exstasy** [comment]
RIP Steam. Кто сидит на мусоре ахуеет подтверждать. + продажи упадут на 50% если не больше) Ну на самом деле надо быть настолько ебанутым чтобы сделать, чтобы ширп подтверждать надо было! Это просто надо быть дцп... Ебнутые вольво)

**Comment by recfunc** [comment]
Вот слегка интересно. Они это делают "для пользы больного"? Или все-таки снижают нагрузку на свои сервера?

**Comment by qwert1223** [comment]
@Exstasy пох ваще)))

**Comment by recfunc** [comment]
@qwert1223 
Да вот не сказал бы. Количество продаж очень сильно просело.
Почему они не могут такие новшества делать опционально и по умолчанию включать - это тоже не понятно.

**Comment by qwert1223** [comment]
@recfunc да тоже заметил, теперь придется ко всем покупкам относиться с не таким похуизмом и не тратить на всё подряд...
