### ISSUE TITLE
Автоконфирматоры

### ISSUE THREAD

**Issue by recfunc** [Maxx53/SCMBot#630]
Я вот тут написал утилиту, для генерации кодов для входа. В основном для себя, конечно, но есть пару идей. В принципе, я могу запилить онлайн авто конфирматор, если народу нужен. Вообще не помешало бы это слегка обговорить... Больше не знаю куда написать, пишу сюда, извините, кого кастанул не по делу.
http://steam-tools.com/two-factor-code-generator/
p.s. кто хочет лично обговорить, милости прошу в skype: **recfunc**

**Comment by G2Dolphin** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator

**Comment by recfunc** [comment]
@G2Dolphin Ога. Спасибо. Зато плачут в каждый трэд, что вручную подтверждать надо :-D
