### ISSUE TITLE
Частота банов

### ISSUE THREAD

**Issue by recfunc** [Maxx53/SCMBot#640]
Что-то последние сутки баны очень часто выдаются, даже при **обычном** просмотре браузером. Как думаете, ошибка стима или что?

**Comment by utka1** [comment]
summer sale(cards made all that panic), prices are slightly going down (ppl try to sell items before sale(=huge drop), to get moar money), so amount of different bot users goes up

**Comment by utka1** [comment]
or those guys just overloading steam servers -> awkward ddos protection by valve
